# Generated by Django 2.2.1 on 2019-07-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_writer',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
