# Generated by Django 2.2.1 on 2019-07-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0013_comment_comment_writer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-pub_date']},
        ),
    ]
